version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    
  backend-web:
    build: ./backend-web
    ports:
      - "5000:5000"
    environment:
      - AI_SERVICE_URL=http://ai-backend:8000
    
  ai-backend:  # Updated service name
    build: ./ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ai-backend/models:/app/models

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=fashion_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
